### ISSUE TITLE
Change speed of playback

### ISSUE THREAD

**Issue by randomekek** [guancio/ChromeOsSubtitle#16]
It is possible to modify the $('video').playbackRate which willl make the video faster or slower. 

Can we get some keybindings (like +/-) for increase/decrease playback speed by 0.1

If i'll get time, I'll submit a patch

**Comment by queuebit** [comment]
+1 (thumbsup)

**Comment by queuebit** [comment]
I was able to manually change the playback speed of a video by inspecting the index.html of the app while playing the video.

I set the playback speed to 2.5x and the subtitles followed along as well.
`$('video')[0].playbackRate = 2.5`

I haven't dove into the code for the controls, but it shouldn't be difficult for someone to add support, I just can't right now.

**Comment by vivekannan** [comment]
Trying using the shortcuts Ctrl + , and Ctrl + . and Ctrl + / to decrease/increase/reset playback speed. The new update will have these shortcuts. @queuebit Your feedback would be very valuable.
