### ISSUE TITLE
Out of Sync Audio

### ISSUE THREAD

**Issue by jwehlitz** [guancio/ChromeOsSubtitle#22]
Hi,

Great program, except for one thing. When I play a local video with this the audio gets out of sync with the video part way through the playback.

Any ideas about how to solve this?

Thanks,

jwehlitz

**Comment by vivekannan** [comment]
Audio delay is now part of the app. If the delay is because of poor video quality, this can solve it. If the problem persists in all videos, I need more data to find the root cause. Closing this issue as it is dead. Open new one if necessary.
