### ISSUE TITLE
New Icon Needed

### ISSUE THREAD

**Issue by d0od88** [guancio/ChromeOsSubtitle#23]
Subtitle Player is a fantastic app that is proving increasing popular with Chromebook owners. But the default app icon leaves a lot to be desired. 

![subtitle icon](https://f.cloud.github.com/assets/869982/2064927/84924492-8cd7-11e3-8b74-524a2ade031b.png)

A new icon should be created or solicited that better matches the polish of the app itself and its unique subtitle features.

**Comment by vivekannan** [comment]
@d0od88 Still interested in making the logo? I am working on my fork of this repo and would really appreciate it if you could come up with some logo.

**Comment by guancio** [comment]
Sorry, but the project has been dormant for a while. Since I found someone interested in maintaining the software ( @vivekannan ) I'm planning to use the icon gently developed by @d0od88
