### ISSUE TITLE
Please, add .ass subtitles support

### ISSUE THREAD

**Issue by austarx** [guancio/ChromeOsSubtitle#26]
I have very large collection of video with .ass subtitles, but I can't play this

**Comment by FiveYellowMice** [comment]
Same here! 
Maybe this project is helpful: <https://github.com/jabbany/ABPlayerHTML5>

**Comment by guancio** [comment]
Unfortunately I do not lot of time to invest on the project. I will try to read the ass specification

**Comment by vivekannan** [comment]
Rudimentary ASS subtitles support has been added to the dev code. It will be released in a few days. It's 'rudimentary' because styling and positioning of the captions is not supported (for now).

**Comment by vivekannan** [comment]
#75 will improve ass support
