### ISSUE TITLE
Change position of subtitles

### ISSUE THREAD

**Issue by thehillprod** [guancio/ChromeOsSubtitle#32]
Is it possible to change the position of the srt? When played via ChromeCast on TV the subs are off screen...

**Comment by opm22** [comment]
it would be nice to have this... Or at least align subtitles with the bottom of the video and not the screen.

**Comment by vivekannan** [comment]
This feature will soon show up in the app. Try using @vivekannan master branch. lots of new features and bug fixes. Your feedback will be very valuable.

**Comment by vivekannan** [comment]
@thehillprod can you explain how you use the app with chromecast? Also, the new version has the subtitle position shortcuts [Ctrl + Shift] + Arrow Keys.
