### ISSUE TITLE
Logging to save the settings of subtitle 

### ISSUE THREAD

**Issue by raimundog** [guancio/ChromeOsSubtitle#34]
It would be nice if you added a logging system to save preferences in the loading subtitles, Such as language, encoding, size ...

**Comment by vivekannan** [comment]
Subtitle size is already stored. Not sure if the stored value is used though. Will check. Not sure what you mean by subtitle language. I just made a pull request with proper fix to remember the selected encoding. #45. You will have to wait until @guancio accepts it and updates his extension.

**Comment by vivekannan** [comment]
Done.
