### ISSUE TITLE
foawrding and rewinding

### ISSUE THREAD

**Issue by ghost** [guancio/ChromeOsSubtitle#35]
whenever i skip with the left or right arrow the whole bottom menu disappears

**Comment by vivekannan** [comment]
Ok. Going to need more info. Try opening the developer console (google if you don't know how) in your browser. With the console open, trying skipping and see if any error get displayed. If so, add a comment here with the exact error text. I will keep looking on my side, but some more info will be very valuable.

**Comment by vivekannan** [comment]
I am closing this issue as it is dead. Please feel free to open a new issue if it still exists.
