### ISSUE TITLE
No video

### ISSUE THREAD

**Issue by raefe** [guancio/ChromeOsSubtitle#38]
When trying to play two separate videos in chrome (https://subtitlevideoplayer.appspot.com/static/ChromeOsSubtitle/src/index.html), none of them load. Does it have to be in a certain directory or does it mean there's a wrong setting in the browser?

**Comment by vivekannan** [comment]
Can you post the videos' file type with codecs and your browser's name and version? Also, did you drap & drop the files or what?

**Comment by vivekannan** [comment]
Dead issue. Closing. Reopen if needed.
