### ISSUE TITLE
Spanish subtitles

### ISSUE THREAD

**Issue by Bmbb** [guancio/ChromeOsSubtitle#39]
All the accented letters in Spanish subtitles are question marks. When opened in a text program, they are displayed correctly. Can this be fixed in some way?

**Comment by vivekannan** [comment]
After selecting your subtitle file, use the closed captions button in the controls to change the encoding from utf-8 to iso-8859-16. That should fix the issue. Note that you have to do this every time you load a subtitle. I will try to find a automatic fix. In the meantime, I hope you can manage with this fix.
