### ISSUE TITLE
where are the downloaded subtitles ?

### ISSUE THREAD

**Issue by b2renger** [guancio/ChromeOsSubtitle#41]
First thanks for the awesome player !

This is a simple usage question : I was wondering where are stored the downloaded substitles ?
I would love to use the auto-download and save the downloaded file to the directory of the video, to be able to use them offline.

**Comment by guancio** [comment]
Unfortunately the current implementation (mainly due to security issue with Chrome does not support this). I would like to implement these features but I've really no time :(

**Comment by b2renger** [comment]
Thanks for the answer it's already awesome as it is.

Maybe I'll research it do you have hints about what kind of stuff it would in

**Comment by vivekannan** [comment]
After going through the source, I think everything from downloading the zip-file to extracting the subs is done in memory (or somewhere deep in chrome's cache). So if you want the subs for off-line use, the extracted sub file should be saved. May need some special permission from the Chrome OS. The related code is near line 152 in opensubtitle.js file. If everything works as expected, the variable 'data' that the anonymous function receives contains the subs and should be saved.

**Comment by guancio** [comment]
You are right. Currently the subtitles are saved in-memory, since writing to the filesystem requires special privileges. This can be implemented with a mechanism similar to the one used for the auto-subtitle folder

**Comment by vivekannan** [comment]
Closing now. Reopen if more clarification needed.
