### ISSUE TITLE
Display newlines properly

### ISSUE THREAD

**Issue by rdancer** [guancio/ChromeOsSubtitle#42]
Currently multi-line subtitles are displayed on a single line; linebreaks are ignored. Sample SRT subtitle file that demonstrates this:  [test-multiline-subtitles.zip](https://github.com/guancio/ChromeOsSubtitle/files/126567/test-multiline-subtitles.zip) (in a ZIP archive, as GitHub won't let me upload it otherwise; I have enclosed a simple blank MP4 file, but any video will do).

The lines should be displayed like this:

> \- Line #1
> \- Line #2 

But they are displayed like this:

> \- Line #1 \- Line #2

**Comment by vivekannan** [comment]
Fixed issue. Checkout the master branch of my fork.

**Comment by rdancer** [comment]
@vivekannan would you care to prepare a release that could be installed in Chrome OS straight away? I installed from https://chrome.google.com/webstore/detail/subtitle-videoplayer/naikohapihpbhficdpbddmgbhiccijca and would not have the first idea how to install on Chrome OS from source, or if it is even possible.

**Comment by vivekannan** [comment]
I don't have owner access to that extension. I will ask @guancio to update the webstore with the fix. I tried mailing him to ask if he needed help with this repository but he still hasn't replied. So you may have to wait a little longer.

**Comment by vivekannan** [comment]
How about I send you a zip file that has all the latest stuff included. I
have made a lot of changes and added some new features as well. Maybe you
can test it for me if you are a frequent user? I normally don't use chrome
OS so it is difficult for me to test it thoroughly. I will also include
instructions to load the zip as an extension.

**Comment by rdancer** [comment]
That would be very kind of you!

No need for instructions, a zipped extension is all I need.

Let me know if there are particular areas that you'd like me to test?

Not sure if it's possible to send via Github; if e-mail is more convenient
for you:
rdancer@rdancer.org

**Comment by vivekannan** [comment]
Hey! I have sent an email with the zip files attached to rdancer@rdancer.org.
Not sure if you got them because it is not in my sent mails. Just checking.

**Comment by rdancer** [comment]
Not received. Please re-send?

**Comment by vivekannan** [comment]
I just sent it again. Could you confirm?

**Comment by rdancer** [comment]
No. Not in spam either. Can you attach it here or upload somewhere & paste a link to it?

**Comment by vivekannan** [comment]
Oops! Never received you last comment. A newer version of the app is now available at the chroome store. Your app should automatically update. Feedback would be valuable.
