### ISSUE TITLE
Arabic encoding subtitle 

### ISSUE THREAD

**Issue by momo00o** [guancio/ChromeOsSubtitle#43]
the arabic encoding subtitle is windows-1256 every time i close the window i have to change it again

**Comment by vivekannan** [comment]
Yes. This is difficult to automate. However, I can add feature so that the last selected encoding is remembered. You would still have to change the encoding manually if the need arises. Give me sometime.

**Comment by vivekannan** [comment]
I have created a pull request with the solution, it is up-to @guancio now.
