### ISSUE TITLE
Autoloading subtitles stopped working after upgrade

### ISSUE THREAD

**Issue by Stangoesagain** [guancio/ChromeOsSubtitle#68]
Select directory menu in settings pops up but subtitles don't autoload.  Is there a problem with reading ~/Downloads/... type shortcuts?

**Comment by vivekannan** [comment]
Give us a few days. Both of us are quite busy right now. General feedback is also appreciated. Assuming autosrt works, which one do you prefer? The old one or the new one?

**Comment by Stangoesagain** [comment]
I use the player with Chromebit, a small stick that plugs into a TV,  so I watch from a few meters away and control it mostly with a mouse. If I ever need to reach for the keyboard then one key shortcuts are better, though I do like 3/10/60 sec option for rewind. 

Ideally I'd like a double click to toggle full screen and mouse wheel to rewind maybe by 5 sec, and maybe a counter how much time left, like on Netflix, but that is not essential. Oh, and counter should be proportional to screen size, otherwise it's too small if watching from a distance.

Good to see you guys returning to this project anyway.

**Comment by vivekannan** [comment]
Time left is available. Try clicking on the current time.

**Comment by vivekannan** [comment]
Yep. Autoloading is broken. A major release will rollout in a few days. Fix will be a part of that. Expect many new features and a MUCH smaller and efficient app.

**Comment by vivekannan** [comment]
Should work with 1.13.0. Closing. Reopen if the issue persists.
