### ISSUE TITLE
Unsupported Codecs

### ISSUE THREAD

**Issue by aghasemi** [guancio/ChromeOsSubtitle#82]
Hi,
Great work. Thanks.
Some files are not played at all, whereas for some others only video is played. I guess it's a codec problem. May I ask whether there is a list of supported codecs?

**Comment by vivekannan** [comment]
Hello!

The app, for now, makes use of HTML5 video tag. So the list of support codecs is decided by the browser. A simple google search (Google Chrome HTML5 codecs) should get you the answer. We do have plans for using flash as a fallback to provide support for MKV and FLV files.

**Comment by aghasemi** [comment]
Thanks. May I ask a technical question: How do you manage to play the files without uploading them to your server? It may look silly but I couldn't find any samples/documents.

**Comment by vivekannan** [comment]
I dont understand. I think you have misunderstood the purpose of the app.
It is meant to used to play video found on your hard disk.

**Comment by vivekannan** [comment]
Nothing is uploaded anywhere, you can switch off your wifi and still use
the app.

**Comment by aghasemi** [comment]
I know, obviously video files aren't uploaded. I got my answer. I meant something like HTML5 File API.

Thanks.

**Comment by vivekannan** [comment]
Closing. Assuming question was answered.
