### ISSUE TITLE
Sound but no images

### ISSUE THREAD

**Issue by PMond57** [guancio/ChromeOsSubtitle#87]
for some MP4 movies I get the sound but there is no images (black screen)

Video: 1 hr 50 min, 720x480, 1975 kb/sec  total 2167 kbits/s  29frames/s, 
Audio: 192 kbits/s, 2 channel (stereo), 48khz

**Comment by vivekannan** [comment]
Yeah. Support for videos is based on the codec. So only certain mp4 files are supported. This support depends on the browser itself and there is very little that we can do. Try using online tools to convert your mp4 file into something like webm. Maybe something like [ClipChamp](https://clipchamp.com/)?

**Comment by vivekannan** [comment]
Closing, please reopen if needed.
